USE [master]
GO
/****** Object:  Database [TSoftMailProjectDB]    Script Date: 8/8/2022 9:49:18 AM ******/
CREATE DATABASE [TSoftMailProjectDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TSoftMailProjectDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TSoftMailProjectDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TSoftMailProjectDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TSoftMailProjectDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [TSoftMailProjectDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TSoftMailProjectDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TSoftMailProjectDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TSoftMailProjectDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TSoftMailProjectDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TSoftMailProjectDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TSoftMailProjectDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [TSoftMailProjectDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TSoftMailProjectDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TSoftMailProjectDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TSoftMailProjectDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TSoftMailProjectDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TSoftMailProjectDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TSoftMailProjectDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TSoftMailProjectDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TSoftMailProjectDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TSoftMailProjectDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TSoftMailProjectDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TSoftMailProjectDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TSoftMailProjectDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TSoftMailProjectDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TSoftMailProjectDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TSoftMailProjectDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TSoftMailProjectDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TSoftMailProjectDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TSoftMailProjectDB] SET  MULTI_USER 
GO
ALTER DATABASE [TSoftMailProjectDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TSoftMailProjectDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TSoftMailProjectDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TSoftMailProjectDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TSoftMailProjectDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TSoftMailProjectDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [TSoftMailProjectDB] SET QUERY_STORE = OFF
GO
USE [TSoftMailProjectDB]
GO
/****** Object:  Table [dbo].[EmailMessages]    Script Date: 8/8/2022 9:49:18 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EmailMessages](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MessageID] [nvarchar](500) NULL,
	[ToAddresses] [nvarchar](50) NULL,
	[FromAddresses] [nvarchar](100) NULL,
	[Subject] [ntext] NULL,
	[Content] [ntext] NULL,
	[MessageDate] [datetime] NULL,
 CONSTRAINT [PK_EmailMessages] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OperationClaims]    Script Date: 8/8/2022 9:49:18 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OperationClaims](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](250) NOT NULL,
 CONSTRAINT [PK_OperationClaims] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserOperationClaims]    Script Date: 8/8/2022 9:49:18 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserOperationClaims](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[OperationClaimId] [int] NOT NULL,
 CONSTRAINT [PK_UserOperationClaims] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 8/8/2022 9:49:18 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](50) NOT NULL,
	[LastName] [varchar](50) NOT NULL,
	[Email] [varchar](50) NOT NULL,
	[PasswordHash] [varbinary](500) NOT NULL,
	[PasswordSalt] [varbinary](500) NOT NULL,
	[Status] [bit] NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [TSoftMailProjectDB] SET  READ_WRITE 
GO
